### ISSUE TITLE
Use phone numer insted of "user_id" (Telegram)

### ISSUE THREAD

**Issue by joelmzj** [neluckoff/social_spam#1]
Hi. Is it possible to use phone number insted of "user_id" when sending a Telegram message?
I'm trying to automate sending messages but it's pretty hard for me generate each user id.

Thanks in advance, you're doing an amazing work!

**Comment by neluckoff** [comment]
Hello!  I did not make such an opportunity, but I can try to implement it.

**Comment by neluckoff** [comment]
Okay, it wasn't that hard.

Now you can get the ID of a telegram user by his number, and then send a message using the received ID.
Example:

```python
user_id = tg.get_id_by_phone('79269019999')
tg.send_message(user_id=user_id, message="Hi! I'm using social_spam package")
```

** This method adds this number to your account, takes its ID and removes this user from your account.
